/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>
#include <otawa/prog/sem.h>

using namespace otawa::sem;

typedef void (*otawa_sem_t)($(proc)_inst_t *inst, ::otawa::sem::Block& block);

static void otawa_sem_UNKNOWN($(proc)_inst_t *inst, ::otawa::sem::Block& block) { }

$(foreach instructions)
static void otawa_sem_$(IDENT)($(proc)_inst_t *inst, ::otawa::sem::Block& block) {
$(otawa_sem)
};

$(end)


/* function table */
static otawa_sem_t $(proc)_sem_table[] =
{
	otawa_sem_UNKNOWN$(foreach instructions),
	otawa_sem_$(IDENT)$(end)
};



/**
 * Get the instruction semantics.
 */
void $(proc)_sem($(proc)_inst_t *inst, ::otawa::sem::Block& block) {
        return $(proc)_sem_table[inst->ident](inst, block);
}
